// Example code for messages generated by a backend function or process.

const AWS = require('aws-sdk')
const iot = new AWS.IotData({endpoint: 'abc123456790-ats.iot.us-east-1.amazonaws.com'})

const params = {
  topic: 'the topic',
  payload: 'the message',
  qos: 0
}

iot.publish(params, (err, data) => {
  if (err) {
    console.log('Error: ', err)
  } else {
    console.log('Success: ', data)
  }
})
